name: TikTokCloneiOS
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: '16.0'
  organizationName: YourCompany
  developmentLanguage: Swift
configurations:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: '16.0'
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    SWIFT_VERSION: 5.0
targets:
  TikTokCloneApp:
    type: application
    platform: iOS
    sources: [TikTokCloneApp/Sources]
    resources: [TikTokCloneApp/Resources]
    dependencies:
      - target: Core
      - target: Feed
      - target: Player
      - target: Post
    settings:
      base:
        OTHER_LDFLAGS: "$(inherited) -ObjC"
  Feed:
    type: framework
    platform: iOS
    sources: [Feed/Sources]
    resources: [Feed/Resources]
    dependencies:
      - target: Core
    settings:
      base:
        OTHER_LDFLAGS: "$(inherited) -ObjC"
  Player:
    type: framework
    platform: iOS
    sources: [Player/Sources]
    resources: [Player/Resources]
    dependencies:
      - target: Core
    settings:
      base:
        OTHER_LDFLAGS: "$(inherited) -ObjC"
  Post:
    type: framework
    platform: iOS
    sources: [Post/Sources]
    resources: [Post/Resources]
    dependencies:
      - target: Core
    settings:
      base:
        OTHER_LDFLAGS: "$(inherited) -ObjC"
  Core:
    type: framework
    platform: iOS
    sources: [Core/Sources]
    resources: [Core/Resources]
    settings:
      base:
        OTHER_LDFLAGS: "$(inherited) -ObjC"

workspaces:
  TikTokCloneiOSs:
    projects:
      - TikTokCloneApp
      - Feed
      - Player
      - Core
      - Post

