name: TikTokCloneiOSs

options:
  bundleIdPrefix: com.yourcompany.TikTokCloneiOS
  deploymentTarget:
    iOS: 16.0

# Main App
targets:
  TikTokCloneApp:
    type: application
    platform: iOS
    sources:
      - path: TikTokCloneApp/Sources/ # Direktori kode sumber aplikasi
    dependencies:
      - target: AppNavigations
      - target: Core
      - target: DataService
      - target: Feed
      - target: Player
      - target: Post
      - target: Pods
      - target: WebViewDetail

include:
  - path: AppNavigations/project.yml
  - path: WebViewDetail/project.yml
  - path: PostWorker/project.yml
  - path: PlayerWorker/project.yml
  - path: Post/project.yml
  - path: Player/project.yml
  - path: Feed/project.yml
  - path: FeedWorker/project.yml
  - path: DataService/project.yml
  - path: Core/project.yml
  - path: Pods/Pods.xcodeproj/project.yml
