name: FeedWorker
options:
  bundleIdPrefix: com.FeedWorker
  deploymentTarget:
    iOS: "16.0"

targets:
  FeedWorker:
    type: framework
    platform: iOS
    sources:
      - FeedWorker
    dependencies:
      - framework: '${BUILT_PRODUCTS_DIR}/Core.framework'
        embed: true
        codeSign: true
      - framework: '${BUILT_PRODUCTS_DIR}/DataService.framework'
        embed: true
        codeSign: true
      - framework: '${BUILT_PRODUCTS_DIR}/Pods_FeedWorker.framework'
        embed: false
        codeSign: false
    settings:
      GENERATE_INFOPLIST_FILE: YES
